# Checks if the build works, 
# by installing the requirements
# and then running the example code

name: ci
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}

      - name: create virtual python environment
        run: conda create -n dna python=3.8

      - name: init conda environment
        run: conda init bash

      - name: activate virtual python environment
        run: conda activate dna

      - name: install required packages
        run: python3 -m pip install -r requirements.txt

      - name: run example code shown in README
        run: python3 .github/workflows/example_huggingface_v4_28.py
    